### ISSUE TITLE
Adicionar mecanismo para verificar se as variáveis de ambientes estão definidas

### ISSUE THREAD

**Issue by willy-r** [otaldonuness/meupetminhavida-back#15]
# Descrição:

Como vamos ter algumas variáveis de ambiente para rodar o projeto, precisamos garantir que as mesmas, ou pelo menos as mais importantes, como a do url do banco de dados, estejam definidas e caso contrário não iniciar o projeto.

Precisamos garantir que as variáveis de ambientes estão definidas corretamente e caso contrário não iniciar o projeto, jogando um erro.

Referência: https://docs.nestjs.com/techniques/configuration

## Tarefas:

- Estudar doc do Nest e escolher melhor forma para garantir que as variáveis estejam definidas
- Implementar mecanismo escolhido

**Comment by allanCordeiro** [comment]
https://github.com/otaldonuness/meupetminhavida-back/tree/15-adicionar-mecanismo-para-verificar-se-as-vari%C3%A1veis-de-ambientes-est%C3%A3o-definidas

**Comment by allanCordeiro** [comment]
After take a look to the nest documentation i've been decided to use the following strategy: https://github.com/otaldonuness/meupetminhavida-back/tree/15-adicionar-mecanismo-para-verificar-se-as-vari%C3%A1veis-de-ambientes-est%C3%A3o-definidas since it create less cognitive load than other options. Also could help us when we start to deploy it on production environment.
